version: "2"

linters:
  enable:
    - gocritic
    - misspell
    - sloglint

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - exitAfterDefer

    sloglint:
      context: "all"

  exclusions:
    paths:
      - "mock_.*\\.go$"
      - ".*_generated\\.go$"
