// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/g3/internal/server (interfaces: Authenticator)
//
// Generated by this command:
//
//	mockgen -destination=mock_authenticator.go -package=server github.com/afreidah/g3/internal/server Authenticator
//

// Package server is a generated GoMock package.
package server

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// AuthenticateAndResolveBucket mocks base method.
func (m *MockAuthenticator) AuthenticateAndResolveBucket(r *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateAndResolveBucket", r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateAndResolveBucket indicates an expected call of AuthenticateAndResolveBucket.
func (mr *MockAuthenticatorMockRecorder) AuthenticateAndResolveBucket(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateAndResolveBucket", reflect.TypeOf((*MockAuthenticator)(nil).AuthenticateAndResolveBucket), r)
}
