// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBucket = `-- name: DeleteBucket :exec
DELETE FROM buckets WHERE name = $1
`

func (q *Queries) DeleteBucket(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteBucket, name)
	return err
}

const getBucket = `-- name: GetBucket :one
SELECT label_id, created_at
FROM buckets
WHERE name = $1
`

type GetBucketRow struct {
	LabelID   string             `json:"label_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetBucket(ctx context.Context, name string) (GetBucketRow, error) {
	row := q.db.QueryRow(ctx, getBucket, name)
	var i GetBucketRow
	err := row.Scan(&i.LabelID, &i.CreatedAt)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT name, label_id, created_at
FROM buckets
ORDER BY name
`

func (q *Queries) ListBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, listBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(&i.Name, &i.LabelID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putBucket = `-- name: PutBucket :exec
INSERT INTO buckets (name, label_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (name)
DO UPDATE SET
    label_id   = EXCLUDED.label_id,
    created_at = EXCLUDED.created_at
`

type PutBucketParams struct {
	Name      string             `json:"name"`
	LabelID   string             `json:"label_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) PutBucket(ctx context.Context, arg PutBucketParams) error {
	_, err := q.db.Exec(ctx, putBucket, arg.Name, arg.LabelID, arg.CreatedAt)
	return err
}
