// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bucket struct {
	Name      string             `json:"name"`
	LabelID   string             `json:"label_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Object struct {
	Bucket      string             `json:"bucket"`
	Key         string             `json:"key"`
	GmailMsgID  string             `json:"gmail_msg_id"`
	DriveFileID string             `json:"drive_file_id"`
	Etag        string             `json:"etag"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}
