// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM objects WHERE bucket = $1 AND key = $2
`

type DeleteObjectParams struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteObject(ctx context.Context, arg DeleteObjectParams) error {
	_, err := q.db.Exec(ctx, deleteObject, arg.Bucket, arg.Key)
	return err
}

const deleteObjectsByBucket = `-- name: DeleteObjectsByBucket :exec
DELETE FROM objects WHERE bucket = $1
`

func (q *Queries) DeleteObjectsByBucket(ctx context.Context, bucket string) error {
	_, err := q.db.Exec(ctx, deleteObjectsByBucket, bucket)
	return err
}

const getObject = `-- name: GetObject :one
SELECT gmail_msg_id, drive_file_id, etag, size, content_type, created_at, metadata
FROM objects
WHERE bucket = $1 AND key = $2
`

type GetObjectParams struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
}

type GetObjectRow struct {
	GmailMsgID  string             `json:"gmail_msg_id"`
	DriveFileID string             `json:"drive_file_id"`
	Etag        string             `json:"etag"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) (GetObjectRow, error) {
	row := q.db.QueryRow(ctx, getObject, arg.Bucket, arg.Key)
	var i GetObjectRow
	err := row.Scan(
		&i.GmailMsgID,
		&i.DriveFileID,
		&i.Etag,
		&i.Size,
		&i.ContentType,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listObjectsAll = `-- name: ListObjectsAll :many
SELECT key, gmail_msg_id, drive_file_id, etag, size, content_type, created_at, metadata
FROM objects
WHERE bucket = $1
  AND key > $2
ORDER BY key
LIMIT $3
`

type ListObjectsAllParams struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
	Limit  int32  `json:"limit"`
}

type ListObjectsAllRow struct {
	Key         string             `json:"key"`
	GmailMsgID  string             `json:"gmail_msg_id"`
	DriveFileID string             `json:"drive_file_id"`
	Etag        string             `json:"etag"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) ListObjectsAll(ctx context.Context, arg ListObjectsAllParams) ([]ListObjectsAllRow, error) {
	rows, err := q.db.Query(ctx, listObjectsAll, arg.Bucket, arg.Key, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsAllRow{}
	for rows.Next() {
		var i ListObjectsAllRow
		if err := rows.Scan(
			&i.Key,
			&i.GmailMsgID,
			&i.DriveFileID,
			&i.Etag,
			&i.Size,
			&i.ContentType,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByPrefix = `-- name: ListObjectsByPrefix :many
SELECT key, gmail_msg_id, drive_file_id, etag, size, content_type, created_at, metadata
FROM objects
WHERE bucket = $1
  AND key LIKE $2
  AND key > $3
ORDER BY key
LIMIT $4
`

type ListObjectsByPrefixParams struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
	Key_2  string `json:"key_2"`
	Limit  int32  `json:"limit"`
}

type ListObjectsByPrefixRow struct {
	Key         string             `json:"key"`
	GmailMsgID  string             `json:"gmail_msg_id"`
	DriveFileID string             `json:"drive_file_id"`
	Etag        string             `json:"etag"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) ListObjectsByPrefix(ctx context.Context, arg ListObjectsByPrefixParams) ([]ListObjectsByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByPrefix,
		arg.Bucket,
		arg.Key,
		arg.Key_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByPrefixRow{}
	for rows.Next() {
		var i ListObjectsByPrefixRow
		if err := rows.Scan(
			&i.Key,
			&i.GmailMsgID,
			&i.DriveFileID,
			&i.Etag,
			&i.Size,
			&i.ContentType,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putObject = `-- name: PutObject :exec
INSERT INTO objects (bucket, key, gmail_msg_id, drive_file_id, etag, size, content_type, created_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (bucket, key)
DO UPDATE SET
    gmail_msg_id  = EXCLUDED.gmail_msg_id,
    drive_file_id = EXCLUDED.drive_file_id,
    etag          = EXCLUDED.etag,
    size          = EXCLUDED.size,
    content_type  = EXCLUDED.content_type,
    created_at    = EXCLUDED.created_at,
    metadata      = EXCLUDED.metadata
`

type PutObjectParams struct {
	Bucket      string             `json:"bucket"`
	Key         string             `json:"key"`
	GmailMsgID  string             `json:"gmail_msg_id"`
	DriveFileID string             `json:"drive_file_id"`
	Etag        string             `json:"etag"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) PutObject(ctx context.Context, arg PutObjectParams) error {
	_, err := q.db.Exec(ctx, putObject,
		arg.Bucket,
		arg.Key,
		arg.GmailMsgID,
		arg.DriveFileID,
		arg.Etag,
		arg.Size,
		arg.ContentType,
		arg.CreatedAt,
		arg.Metadata,
	)
	return err
}
