// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/g3/internal/backend (interfaces: ObjectBackend)
//
// Generated by this command:
//
//	mockgen -destination=mock_backend.go -package=backend github.com/afreidah/g3/internal/backend ObjectBackend
//

// Package backend is a generated GoMock package.
package backend

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectBackend is a mock of ObjectBackend interface.
type MockObjectBackend struct {
	ctrl     *gomock.Controller
	recorder *MockObjectBackendMockRecorder
	isgomock struct{}
}

// MockObjectBackendMockRecorder is the mock recorder for MockObjectBackend.
type MockObjectBackendMockRecorder struct {
	mock *MockObjectBackend
}

// NewMockObjectBackend creates a new mock instance.
func NewMockObjectBackend(ctrl *gomock.Controller) *MockObjectBackend {
	mock := &MockObjectBackend{ctrl: ctrl}
	mock.recorder = &MockObjectBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectBackend) EXPECT() *MockObjectBackendMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockObjectBackend) CreateBucket(ctx context.Context, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", ctx, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockObjectBackendMockRecorder) CreateBucket(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockObjectBackend)(nil).CreateBucket), ctx, bucket)
}

// DeleteObject mocks base method.
func (m *MockObjectBackend) DeleteObject(ctx context.Context, bucket, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucket, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectBackendMockRecorder) DeleteObject(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectBackend)(nil).DeleteObject), ctx, bucket, key)
}

// GetObject mocks base method.
func (m *MockObjectBackend) GetObject(ctx context.Context, bucket, key string) (*GetObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucket, key)
	ret0, _ := ret[0].(*GetObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectBackendMockRecorder) GetObject(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectBackend)(nil).GetObject), ctx, bucket, key)
}

// HeadObject mocks base method.
func (m *MockObjectBackend) HeadObject(ctx context.Context, bucket, key string) (*HeadObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, bucket, key)
	ret0, _ := ret[0].(*HeadObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockObjectBackendMockRecorder) HeadObject(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockObjectBackend)(nil).HeadObject), ctx, bucket, key)
}

// ListBuckets mocks base method.
func (m *MockObjectBackend) ListBuckets(ctx context.Context) ([]BucketInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuckets", ctx)
	ret0, _ := ret[0].([]BucketInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuckets indicates an expected call of ListBuckets.
func (mr *MockObjectBackendMockRecorder) ListBuckets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuckets", reflect.TypeOf((*MockObjectBackend)(nil).ListBuckets), ctx)
}

// ListObjects mocks base method.
func (m *MockObjectBackend) ListObjects(ctx context.Context, bucket, prefix, delimiter, startAfter string, maxKeys int) (*ListObjectsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucket, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectBackendMockRecorder) ListObjects(ctx, bucket, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectBackend)(nil).ListObjects), ctx, bucket, prefix, delimiter, startAfter, maxKeys)
}

// PutObject mocks base method.
func (m *MockObjectBackend) PutObject(ctx context.Context, bucket, key string, body io.Reader, size int64, contentType string, metadata map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucket, key, body, size, contentType, metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectBackendMockRecorder) PutObject(ctx, bucket, key, body, size, contentType, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectBackend)(nil).PutObject), ctx, bucket, key, body, size, contentType, metadata)
}
