#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if systemctl is-active --quiet g3 2>/dev/null; then
        systemctl stop g3
    fi
    if systemctl is-enabled --quiet g3 2>/dev/null; then
        systemctl disable g3
    fi
fi
